config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'register' => 'users#new'
  get 'users/edit'
  get 'users/show'
  get 'users/index'

  resources :companies do
    resources :departments
    resources :employees
  end

  resources :users
  resources :articles

  get 'new-company' => 'companies#new'
  get 'mycompanies' => 'companies#index'
  get 'companies/new'
  get 'companies/edit'
  get 'companies/show'

  get 'employees/new'
  get 'employees/edit'
  get 'employees/index'
  get 'employees/show'
  get 'departments/new'
  get 'departments/edit'
  get 'departments/show'
  get 'departments/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/write' => 'articles#new'
  get 'articles/edit'
  get 'articles/show'
  get 'articles/index'
  get '/search' => 'articles#search'
  get '/results' => 'articles#results'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :cover_photo
  belongs_to :user
  validates :title, :content, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :departments
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department

  def full_name
    self.first_name + " " + self.last_name
  end

  def generate_eid
    self.eid = SecureRandom.hex(3).upcase
  end

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_one_attached :photo
  has_many :articles
  has_secure_password
  validates :password, presence: true, length: { maximum: 32, minimum: 8 }
  validates :email, presence: true, length: { maximum: 100 }
  def full_name
    self.first_name + " " + self.last_name
  end

  def generate_eid
    self.eid = SecureRandom.hex(3).upcase
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update]

  def new
    @article = Article.new
  end

  def create
    # POST /articles
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.author = current_user.full_name
    if @article.save
      p "article saved!"
      redirect_to @article
    else
      p 'Article rejected for errors'
      p @article.errors.messages
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      p "article successfully updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
  end

  def index
    # GET /articles
    @articles = Article.all.order('CREATED_AT DESC')
  end

  def search

  end

 def results
   @results = params[:q]
   p params[:date_submitted]
   # if params[:terms].to_i != 1
   #   p 'User did not agree :/'
   #   render 'search'
   # end
   search_words = params[:q].downcase.split(' ')
   titles = Article.pluck(:title)
   matches = []
   @final_results = []
   search_words.each do |word|
     titles.each do |t|
       if t.downcase.include?(word)
         matches << t
       end
     end
   end
   matches.each do |match| #2
       x = Article.where(title: match) #2
       x.each do |y|
         @final_results << y
       end
   end
   @final_results
 end

  private

  def article_params
    params.require(:article).permit(:title, :author, :content, :cover_photo)
  end

  def find_article
    @article = Article.find(params[:id])
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_company, only: [:show, :edit]

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @company = Company.find(params[:id])
  end

  def index
    @companies = Company.where(user_id: current_user.id)
  end

  private

  def company_params
    params.require(:company).permit(:name, :industry)
  end

  def find_company
    @company = Company.find(params[:id])
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @company = Company.find(params[:company_id])
    @employee = Employee.new
    @depts = Department.where(company_id: @company.id)
  end

  def create
    @company = Company.find(params[:company_id])
    @employee = Employee.new(employee_params)
    @employee.company_id = @company.id
    @employee.generate_eid
    if @employee.save
      msg = "New Employee created!"
      redirect_to company_path(@employee.company_id)
    else
      render 'new'
    end
  end


  def edit
  end

  def index
  end

  def show
  end

  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :department_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # AUTHENTICATION => You are who you say you are
  # AUTHORIZATION  => What privileges does this person have?


  def new
  end

  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in(user)
        redirect_to root_path
      else
        msg = "Invalid credentials"
        p msg
        render 'new'
      end
  end


  def destroy
    session[:user_id] = nil
    log_out if logged_in?
    p 'Logged out successfully'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.generate_eid
    if @user.save
      msg = "Registration complete!"
      flash[:notice] = msg
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :bio, :photo, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def long_article?(a)
    if a.content.split('').count > 100
      msg = 'You may want to read this later'
    else
      msg = 'This is a quick read'
    end
    return msg
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<ul>
  <li><%= link_to 'Register', register_path %></li>
  <li><%= link_to 'All Articles', articles_path %></li>
  <li><%= link_to 'Write an Article', write_path %></li>
  <li><%= link_to 'Search', search_path %></li>
  <% if logged_in? %>
    <li><%= link_to "#{current_user.email}", '#' %></li>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Log In', login_path %></li>
  <% end %>
</ul>

app/views/layouts/_header_ent.html.erb
<ul>
  <li><%= link_to "Home", root_path %></li>
  <% if logged_in? %>
    <li><%= link_to "#{current_user.email}", mycompanies_path %></li>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    <li><%= link_to 'Create Company', new_company_path %></li>
  <% else %>
    <li><%= link_to 'Register', register_path %></li>
    <li><%= link_to 'Log In', login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enterprise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header_ent' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome to HR Enterprise</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<% if logged_in? %>
 You are logged in
<% end %>

app/views/shared/_messages.html.erb
<% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
<% end %>